"""initial migration

Revision ID: 198cb9e1fc39
Revises: 
Create Date: 2025-06-13 20:31:10.298317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '198cb9e1fc39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earthquakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('magnitude', sa.Float(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('earthquakes')
    # ### end Alembic commands ###
